language: cpp
compiler: gcc
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-all-dev -y
  - sudo apt-get install ruby rubygems -y
  - sudo gem install bundler
  - sudo bundle install
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./devel/lib/soundex/test/FeatureShowcaseSteps &
  - cd ../cpp/lib/soundex/test
  - cucumber
