language: cpp
os:
  - linux
sudo: required
compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-all-dev -y
  - sudo apt-get install ruby rubygems -y
  - sudo gem install bundler -y
  - bundle install
script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./devel/lib/soundex/test/FeatureShowcaseSteps &
  - cd ../cpp/lib/soundex/test
  - bundle exec cucumber
