language: cpp
compiler: gcc
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install ruby 2.2.0 rubygems
  - sudo gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  - sudo curl -sSL https://get.rvm.io | bash -s stable --ruby
  - sudo rvm install 2.1.1
  - sudo rvm use 2.1.1
  - ruby -v
  - sudo gem install cucumber
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./devel/lib/soundex/test/FeatureShowcaseSteps &
  - cd ../cpp/lib/soundex/test
  - cucumber
