language: cpp
compiler: gcc
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-all-dev
  - mkdir tmp && cd /tmp
  - wget http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.2.tar.gz
  - tar -xvzf ruby-2.1.2.tar.gz
  - cd ruby-2.1.2/
  - ./configure --prefix=/usr/local
  - make
  - sudo make install
  - sudo apt-get  ruby rubygems
  - sudo gem install cucumber
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./devel/lib/soundex/test/FeatureShowcaseSteps &
  - cd ../cpp/lib/soundex/test
  - cucumber
