language: cpp
compiler: gcc
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-all-dev -y
  - sudo apt-add-repository ppa:brightbox/ruby-ng -y
  - sudo apt-get update
  - sudo apt-get install ruby2.2 ruby2.2-dev -y
  - sudo apt-get install rubygems -y
  - sudo gem install cucumber -y
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./devel/lib/soundex/test/FeatureShowcaseSteps &
  - cd ../cpp/lib/soundex/test
  - cucumber
