language: cpp
os:
  - linux
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - clang-3.6
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-all-dev -y
  - sudo apt-get install ruby rubygems-integration -y
  - sudo gem install bundler -y
  - bundle install
script:
  - mkdir build && cd build && cmake .. && make
  - ./lib/soundex/test/FeatureShowcaseSteps &
  - cd ../lib/soundex/test && bundle exec cucumber
