language: cpp
compiler: gcc
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libboost-all-dev
  - sudo apt-add-repository -y ppa:brightbox/ruby-ng
    - sudo apt-get update
  - sudo apt-get install -y ruby2.2 ruby2.2-dev
  - sudo apt-get install -y rubygems2.2
  - sudo gem install -y cucumber
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./devel/lib/soundex/test/FeatureShowcaseSteps &
  - cd ../cpp/lib/soundex/test
  - cucumber
