version: "{branch}-ci-{build}"
os: Visual Studio 2015

environment:
  RUBY_VERSION: 200
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_59_0\boost
  matrix:
  - platform: x86
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0
  - platform: x64
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0

install:
- set PATH=C:\Ruby%RUBY_VERSION%\bin;%BOOST_LIBRARYDIR%;%PATH%
- gem install bundle
- bundle install
- bundle env

build_script:
- cmd: call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%
- cmd: cmake -E make_directory build
- cmd: cmake -E chdir build cmake -G "NMake Makefiles" ..
- cmd: cmake --build build

test_script:
- cmd: ./lib/soundex/test/FeatureShowcaseSteps.exe &
- cmd: cd ../lib/soundex/test && bundle exec cucumber

branches:
  only:
  - master

notifications:
- provider: Email
  to:
  - andy.augustin@t-online.de
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
